### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by dvd2000**
I just translated the comments in the code in English and added some content in the README file.

### CODE REVIEW

**Comment by Darker** [comment]
Thanks a bunch! It's great to see this repo was finally useful to someone adter all the years :)

**Comment by dvd2000** [comment]
The two libraries you've written are really useful. I've would really like to contribute more to this repo, what do you think I can focus on? Maybe I can write some other libraries for the UI.
P.S. When I forked the repo I changed its name (also in the README), you should modify the README or change the project name.

**Comment by Darker** [comment]
I can upload few more libraries a worked on but I can't test any more because I don't have access to NXT brick any more. I think the repository name promoting the name NXC is best for SEO, and yor readme is awesome for specific google searches. If you're really commited to work on this more, I will upload my filre-settings library which I used for saving PID constant values. I will have to find it and add comments to it, so only say yes if you're ready for someone else's piece of code.

Also I will add you as repository contributor, because you're clearly more capable than me right now.

**Comment by dvd2000** [comment]
Yes, I'm really interested in this project and a would like to write some other libraries. I've yet some ideas, but if you have already started to wrote something, I think it would be better if I first can watch your code. We can create a testing branch for code that should be tested or you can send me your code by email and I can test it on the NXT and, if needed, make some changes.

**Comment by dvd2000** [comment]
Or you can also make a pull request and assign it to me. I don't know very well GitHub so I don't know what is the typical way to do that, tell me how do you prefer. I think a testing branch will be a good idea because we can work on new libraries and then add them to the master branch more easily, but I think that working with pull requests can be a bit more easy.
Anyway, if I have some ideas or proposals that I think you should review I should use "issues"?

**Comment by Darker** [comment]
I think I will send you all my nxc code over email and you can pick what's useful. Use issues only for problems that might be useful to other visitors - otherwise you can also just email me. However I am not so sure I will be helpful now that I can't test any code.

I will send you all files I can find on my computer when I get home, which is at about 19:00 UTC.

Making a second branch is sure a good idea, go ahead if you want.

**Comment by Darker** [comment]
Hi, I finally have sent you the files. I hope some of it will be useful.

**Pull request merged**
